spring.application.name=library-management

spring.datasource.url=jdbc:mysql://library-mysql-hieu.mysql.database.azure.com:3306/library_db?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=mysqladmin
spring.datasource.password=hieu@1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=library-management-secret-key-2026-library-management-secret
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=1209600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true